name: flix_id
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.4.1"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.19.0
  firebase_auth: ^4.11.1
  cloud_firestore: ^4.11.0
  firebase_storage: ^11.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.1
  flutter_riverpod: ^2.4.6
  path: ^1.8.3
  dio: ^5.3.4
  go_router: ^13.2.0
  google_fonts: 6.1.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_easyloading: ^3.0.5
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  custom_lint: ^0.5.6
  test: ^1.25.2

flutter:
  uses-material-design: true

  assets:
    - assets/
